CREATE TABLE Sach(
MaSach	VARCHAR(10) PRIMARY KEY,
TenSach	NVARCHAR(40) NOT NULL,
ISBN	VARCHAR(20) NOT NULL,
ViTri	VARCHAR(10) NOT NULL,
NgonNgu	NVARCHAR(20) NOT NULL,
TrangThai NVARCHAR(10) NOT NULL
)
GO
ALTER TABLE Sach ADD CONSTRAINT CHK_TT CHECK (TrangThai IN (N'Có Sẵn', N'Được Mượn', N'Thất Lạc'))
GO
--TAO BANG NXB
CREATE TABLE NhaXuatBan(
MaNXB VARCHAR(10) PRIMARY KEY,
TenNXB NVARCHAR(40) NOT NULL
)
GO
--TAO BANG THELOAI
CREATE TABLE TheLoai(	
MaTL	VARCHAR(10) PRIMARY KEY,
TenTL	NVARCHAR(40) NOT NULL
)
GO
--TAO BANG TACGIA
CREATE TABLE TacGia(	
MaTG	VARCHAR(10) PRIMARY KEY,
TenTG	NVARCHAR(40) NOT NULL
)
GO
--TAO BANG SACH_NXB
CREATE TABLE SachNhaXuatBan(	
MaSach	VARCHAR(10) NOT NULL,
MaNXB	VARCHAR(10) NOT NULL
CONSTRAINT PK_SACH_NXB PRIMARY KEY(MaSach, MaNXB)
)
GO
ALTER TABLE SachNhaXuatBan ADD CONSTRAINT FK_SACH_NXB FOREIGN KEY (MaSach) REFERENCES Sach(MaSach)
GO
ALTER TABLE SachNhaXuatBan ADD CONSTRAINT FK_NXB FOREIGN KEY (MaNXB) REFERENCES NhaXuatBan(MaNXB)
GO

--TAO BANG SACH_TG
CREATE TABLE SachTacGia(	
MaSach	VARCHAR(10) NOT NULL,
MaTG	VARCHAR(10) NOT NULL
CONSTRAINT PK_SACH_TG PRIMARY KEY(MaSach, MaTG)
)
GO
ALTER TABLE SachTacGia ADD CONSTRAINT FK_SACH_TG FOREIGN KEY (MaSach) REFERENCES Sach(MaSach)
GO
ALTER TABLE SachTacGia ADD CONSTRAINT FK_TG FOREIGN KEY (MaTG) REFERENCES TacGia(MaTG)
GO

--TAO BANG SACH_TL
CREATE TABLE SachTheLoai(
MaSach	VARCHAR(10) NOT NULL,
MaTL	VARCHAR(10) NOT NULL
CONSTRAINT PK_SACH_TL PRIMARY KEY(MaSach, MaTL)
)
GO

ALTER TABLE SachTheLoai ADD CONSTRAINT FK_SACH_TL FOREIGN KEY (MaSach) REFERENCES Sach(MaSach)
GO
ALTER TABLE SachTheLoai ADD CONSTRAINT FK_TL FOREIGN KEY (MaTL) REFERENCES TheLoai(MaTL)
GO
--TAO BANG DOC GIA
CREATE TABLE DocGia(
MaDG	VARCHAR(10) PRIMARY KEY,
TenDG NVARCHAR(40) NOT NULL,
Email	VARCHAR(10) NOT NULL,
SDT		VARCHAR(10) NOT NULL,
CCCD	VARCHAR(10) NOT NULL
)
GO
--TAO BANG DONMUON
CREATE TABLE DonMuon(	
MaMuon	VARCHAR(10) PRIMARY KEY,
MaDG	VARCHAR(10) NOT NULL,
MaNV VARCHAR(10) NOT NULL,
NgayMuon	SMALLDATETIME NOT NULL,
NgayTraDK	SMALLDATETIME NOT NULL,
NgayTraTT	SMALLDATETIME,
PhiPhat	MONEY
)
GO
ALTER TABLE DonMuon ADD CONSTRAINT FK_DONMUON_DG FOREIGN KEY (MaDG) REFERENCES DocGia(MaDG)
GO
ALTER TABLE DonMuon ADD CONSTRAINT FK_DONMUON_NV FOREIGN KEY (MaNV) REFERENCES TaiKhoan(UserID)
GO
--TAO BANG CTDM
CREATE TABLE CTDM(	
MaMuon	VARCHAR(10) NOT NULL,
MaSach	VARCHAR(10) NOT NULL
CONSTRAINT PK_CTDM PRIMARY KEY(MAMUON, MASACH)
)
GO
ALTER TABLE CTDM ADD CONSTRAINT FK_CTDH_SACH FOREIGN KEY (MaSach) REFERENCES Sach(MaSach) 
ALTER TABLE CTDM ADD CONSTRAINT FK_CTDH_MUON FOREIGN KEY (MaMuon) REFERENCES DonMuon(MaMuon)

--TAO BANG TAIKHOAN
CREATE TABLE TaiKhoan(
UserID	VARCHAR(10) PRIMARY KEY,
UserNAME	NVARCHAR(40) NOT NULL,
Password	NVARCHAR(40) NOT NULL,
Loai	CHAR(2) NOT NULL,
Email	VARCHAR(10) NOT NULL,
SDT		VARCHAR(10) NOT NULL,
CCCD	VARCHAR(10) NOT NULL
)
GO
ALTER TABLE TaiKhoan ADD CONSTRAINT CHK_TK_LOAI CHECK(Loai IN('NV', 'AD'))
GO
